[build-system]
requires = ["setuptools >= 61.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "bernstein_flow"
readme = "README.md"
requires-python = ">=3.7, <=3.9"
license = {text = "Apache Software License (Apache 2.0)"}
classifiers = [
    "Programming Language :: Python :: 3.7",
]
dependencies = [
        "tensorflow>=2.5.*, <2.10",
        "tensorflow_probability>=0.13.*, <0.17",
        "matplotlib",
]
dynamic = ["version"]

[project.optional-dependencies]
train = [
  'pandas',
  'PyYAML'
]
develop = [
    'bernstein_flow[train]',
    'autoflake',
    'black',
    'isort',
    'pre-commit',
    'pytest',
    'pytest-xdist',
    'python-lsp-black',
    'python-lsp-server[all]',
]

[tool.setuptools.dynamic]
version = {attr = "bernstein_flow.__version__"}

[tool.autoflake]
check = true
expand-star-imports = true
remove-unused-variables = true
ignore-init-module-imports = true
remove-all-unused-imports = true

[tool.isort]
profile = "black"
