[build-system]
requires = ["setuptools >= 61.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "bernstein_flow"
readme = "README.md"
requires-python = ">=3.7"
license = {text = "Apache Software License (Apache 2.0)"}
classifiers = [
    "Programming Language :: Python :: 3.7",
]
dependencies = [
        "tensorflow_probability>=0.13.*, <=0.18.*",
        "matplotlib",
]
dynamic = ["version"]

[project.optional-dependencies]
train = [
  'pandas',
  'PyYAML'
]
develop = [
    'bernstein_flow[train]',
    'pytest',
    'black',
    'isort',
    'python-lsp-server[all]',
    'python-lsp-black',
]

[tool.setuptools.dynamic]
version = {attr = "bernstein_flow.__version__"}
