bimodal:
  fit_kwds:
    output_shape: 20
    extrapolation: quadratic
    thetas_constrain_fn:
      !!python/object/apply:bernstein_flow.activations.get_thetas_constrain_fn
      kwds:
        allow_values_outside_support: false
        constrain_second_drivative: turn
        # support: false
        # fn: !!python/name:tensorflow.abs

    clip_to_bernstein_domain: false
    scale_base_distribution: true
    # clip_base_distribution: true
    scale_data: true
    shift_data: true
  data_points: 4000
  scale_data_to_domain: false
