bimodal:
  fit_kwds:
   support: null
   output_shape: 23
   bb_class: !!python/name:bernstein_flow.bijectors.bernstein_extra.BernsteinBijectorLinearExtrapolate
   allow_values_outside_support: true
   clip_base_distribution: false
   clip_to_bernstein_domain: false
   scale_base_distribution: true
   scale_data: true
   shift_data: true
  scale_data_to_domain: false
