bimodal:
  fit_kwds:
   output_shape: 20
   scale_base_distribution: true 
   scale_data: true
   shift_data: true
   support: null
   allow_values_outside_support: false
  scale_data_to_domain: false
