bimodal:
  fit_kwds:
    batch_size: 32
    epochs: 1000
    # steps_per_epoch: 2
  model_kwds:
    output_shape: 20
    thetas_constrain_fn: !!python/object/apply:bernstein_flow.activations.get_thetas_constrain_fn
      kwds:
        low: -3
        high: 3
        smooth_bounds: true
        allow_flexible_bounds: true
        # fn: !!python/name:tensorflow.square
    # clip_base_distribution: true
    clip_to_bernstein_domain: false
    scale_base_distribution: false
    scale_data: true
    shift_data: true
    extrapolation: true
  scale_data_to_domain: false
