name: train and evaluate old faithful model

on: [push]

jobs:
  run:
    runs-on: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2

    - uses: iterative/setup-cml@v1

    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: cml
      env:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
      run: |
        pip install '.[train]'
        python cml/old_faithful.py

        echo '# Old Faithful' >> report.md

        echo '## Learning Curve' >> report.md
        echo '![](metrics/old_faithful/of_hist.png)' >> report.md

        echo '## Metrics' >> report.md
        cat metrics/old_faithful/of_metrics.txt >> report.md

        echo '## Parameter Vector' >> report.md
        cat metrics/old_faithful/of_pvector.txt >> report.md

        echo '## Results' >> report.md
        echo '![](metrics/old_faithful/of_dist.png)' >> report.md
        cml comment create report.md
