name: "train and evaluate old faithful model"

on: [push]

jobs:
  run:
    runs-on: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2

      - uses: iterative/setup-cml@v1

      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: cml
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
              pip install .
              pip install pandas
              python cml/old_faithful.py

              echo '# Old Faithful' >> report.md
              
              echo '## Learning Curve' >> report.md
              cml-publish metrics/of_hist.png --md >> report.md

              echo '## Metrics' >> report.md
              cat metrics/of_metrics.txt >> report.md
              
              echo '## Parameter Vector' >> report.md
              cat metrics/of_pvector.txt >> report.md
              
              echo '## Results' >> report.md
              cml-publish metrics/of_dist.png --md >> report.md
              cml-send-comment report.md
