name: train and evaluate old faithful model
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - uses: actions/setup-node@v1
      with:
        node-version: '16'
    - uses: iterative/setup-cml@v1
    - name: Install TeXlive
      run: sudo apt-get update && sudo apt-get install texlive texlive-science texlive-latex-extra cm-super dvipng
    - name: cml
      env:
        REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        pip install '.[train]'
        python cml/old_faithful.py

        echo '# Old Faithful' >> report.md

        echo '## Learning Curve' >> report.md
        echo '![](artifacts/old_faithful/of_hist.png)' >> report.md

        echo '## Metrics' >> report.md
        cat metrics/old_faithful/of_metrics.txt >> report.md

        echo '## Parameter Vector' >> report.md
        cat artifacts/old_faithful/of_pvector.txt >> report.md

        echo '## Flow' >> report.md
        echo '![](artifacts/old_faithful/of_flow.png)' >> report.md

        echo '## Results' >> report.md
        echo '![](artifacts/old_faithful/of_dist.png)' >> report.md
        cml comment create report.md
